<link rel="stylesheet" href="css/about.css">

<div class="container">
    <section class="section_about ud-p-30">
        <article class="section_about_article">
            <div class="section_about_article_bloc1 ud-p-50">
                <h2 class="ud-p-20 c-green">Qui suis-je ?</h2>
                <img class="img1" src="https://via.placeholder.com/500x350" alt="">
                <p>Ancienne gymnaste, coach sportif diplômée, professeur certifiée de yoga Hatha et Vinyasa, professeur de Pilates, de Cycling, Elise Vanetti cumule les casquettes et s’en régale. Sa mission préferée : aider les autres à se sentir bien dans leur peau. Passionnée et cumulant sept ans d’expérience dans le métier, sa règle d’or est une citation de Gandhi : « Vis comme si tu devais mourir demain, apprend comme si tu devais vivre toujours. »
                Sa prochaine formation dans le viseur ? Le yoga prénatal, afin de prendre soin des femmes enceintes ou qui viennent d’accoucher. Sa douloureuse expérience post-accouchement en 2017 l’a bouleversée mais l’a aussi réveillée : Ce qui ne tue pas rend clairement plus fort ! 
                Plus de détails dans la rubrique« <a class="normal-link" href="#parcours">Mon parcours</a>  »</p>
            </div>
            <hr>
            <div class="section_about_article_bloc2 ud-p-50" id="parcours">
                <h2 class="ud-p-20 c-green">Mon parcours</h2>
                <img class="img2" src="https://via.placeholder.com/500x350" alt="">
                <p>A tout juste 24 ans, salariée d’une agence de presse parisienne et  jeune maman  je décide de m’inscrire au concours de coach sportif. Loin d’être capable de faire la moindre pompe à ce moment-là, personne ne me prend au sérieux. Pourtant je le sais au fond de moi, je vais adorer ce métier. 
                Mes 10 kilos de trop et mon bébé dans le cosy, je pars m’inscrire à la salle de sport… Je me souviens encore du rire du commercial quand je lui ai parlé de mon projet ! Je reste pourtant déterminée. Au fil des semaines, non sans mal, je me rapproche peu à peu des scores à atteindre dans chaque épreuve du concours. En réalité, je prépare non pas un mais deux concours : en Fitness et en Musculation. Quelques mois plus tard, je suis admise à l’Insep. Jongler avec les devoirs à rendre, les courbatures et les biberons n’aura pas été de tout repos. Mener de front mes études et mon rôle de maman a été une expérience difficile mais extrêmement formatrice et enrichissante.

                Par la suite j’ai travaillé dans de nombreuses salles de sport, les petites comme les prestigieuses, en banlieue comme à  Paris, en passant par les comités d’entreprises et par énormément de coaching privés. De précieuses expériences qui m’apprennent beaucoup sur le corps et l’être humain. 

                En 2017, enceinte de mon deuxième enfant, mon médecin m’impose de lever le pied pour le bien de la grossesse. Habituée à enseigner des cours intenses et du Cycling, j’accepte avec plaisir de m’orienter vers l’enseignement du Pilates, ainsi que du body balance, un cours de yoga informel. Si le Pilates est connu et reconnu, le body balance, lui, a l’inconvénient d’être non homologué par la fédération française de yoga. Attirée par cette discipline, je décide d’ajouter une corde à mon arc en projetant de m’inscrire juste après l’accouchement à la très officielle formation de professeur de yoga. 
                Malheureusement, des soucis de santé post accouchement freinent considérablement mes projets. Affaiblie physiquement mais chanceuse de ne garder aucunes séquelles, je reviens plus forte et déterminée vers mon projet yoga avec ce petit « truc » en plus. 
                Ma douloureuse expérience à l’hôpital aura eu le mérite de faire changer mon regard sur la vie. Un regard rempli de gratitude à l’égard du Mouvement avec un grand M, une nouvelle passion pour la philosophie yogique, un besoin sincère de côtoyer la nature,m’obligent à me tourner vers une vie encore plus saine et une pratique sportive plus respectueuse. Moi qui aurait pu ne plus jamais pouvoir bouger, se tourner vers le yoga devient alors une évidence, bien plus qu’un simple moyen d’élargir mes compétences professionnelles.

                Aujourd’hui, c’est avec joie que j’ouvre mon premier studio pluridisciplinaire que je ne pouvais imaginer ailleurs qu’au beau milieu d’un jardin verdoyant. Avec beaucoup de plaisir je transmettrai mon savoir-faire à mes élèves afin d’offrir une expérience corps-esprit unique.  

                Merci pour votre lecture. 

                Elise  </p>
            </div>
        </article>
    </section>
</div>