<link rel="stylesheet" href="css/concept.css">

<div class="container_2">
    <section id="concept" class="index_section_concept ud-p-30" id="concept">
        <h1 class="w100 t-a-center c-green">Le Concept</h1>
        <p class="w-80 m-auto ud-p-20" style="text-align: justify;">Le Garden studio est né parce que j’avais très envie de travailler dans un studio à mon image et dans lequel mes élèves puissent se sentir vraiment bien. Cassant tous les codes, il est l’anti-salle de sport. Sous une verrière transparente avec vue panoramique sur jardin, le Garden studio est petit et il a choisi d’en faire un atout : il n’accueille que 6 élèves maximum par cours afin d’offrir un enseignement privilégié et à l’écoute de chacun. 
        Baies vitrées grandes ouvertes lorsqu’il fait beau, la frontière s’efface entre le dedans et le dehors. Baigné de lumière, la connexion avec la nature rend la pratique magique et l’effort plus agréable. A l’opposé des salles de sports et de ses diktats, le Garden studio est un havre de paix où vous pourrez faire du sport sans avoir peur de la foule ni du regard des autres. Venez en faire votre QG, votre bol d’air, votre sanctuaire ! Le meilleur endroit pour être bien dans sa peau c’est le Garden studio !</p>

        <div class="index_section_concept_bloc fl-jc-b">
            <article data-aos="fade"
                data-aos-offset="200"
                data-aos-delay="50"
                data-aos-duration="2000"  
                class="w-60 p-20 ud-m-20 t-a-center">
                <h2 class="ud-p-10 c-green"><i class="w-100 fas fa-dumbbell"></i>Bougez-vous et détendez-vous </h2>
                <p class="ud-p-10">Ici on peut faire du yoga en écoutant les oiseaux chanter, du pilates sur de la bonne musique, mais on peut aussi suer à grosses gouttes sur des circuits-trainings endiablés. 
                </p>
            </article>
            <article data-aos="fade"
                data-aos-offset="200"
                data-aos-delay="50"
                data-aos-duration="2000" class="w-30 p-20 ud-m-20 t-a-center">
                <h2 class="ud-p-10 c-green"><i class="w-100 fas fa-mug-hot"></i>Prélassez-vous </h2>
                <p class="ud-p-10">Avant ou apres l’effort, on peut chiller dans une pièce soigneusement décorée autour d’un thé, d’une eau infusée, d’un café ou même d’un cappucino ! Et c’est bien-sûr gratuit.
                </p>
            </article>
            <article data-aos="fade"
                data-aos-offset="200"
                data-aos-delay="50"
                data-aos-duration="1000" class="w-100 p-20 ud-m-20 t-a-center">
                <h2 class="ud-p-10 c-green"><i class="w-100 fas fa-hot-tub"></i> Pomponnez-vous </h2>
                <p class="ud-p-10">On peut se changer dans un vestiaire qui ne ressemble vraiment pas aux vestiaires froids et tristes des salles de sport. Pas de risque d’avoir froid aux pieds ou de perdre sa clé de casier !
                Une salle de bain attenante au vestiaire est à votre disposition avec tout le nécéssaire pour que vous puissiez vous doucher et vous remaquiller si vous le souhaitez : serviettes, produits de beauté, protections périodiques, élastiques et sèche-cheveux sont en libre accès afin que vous puissiez venir les mains vides.
                </p>
            </article>
            <article data-aos="fade"
                data-aos-offset="200"
                data-aos-delay="50"
                data-aos-duration="1000" class="w-30 p-20 ud-m-20 t-a-center">
                <h2 class="ud-p-10 c-green"><i class="w-100 fas fa-shopping-bag"></i> Allégez-vous</h2>
                <p class="ud-p-10">Sauf si vous préférez venir avec votre propre tapis, le Garden studio a pris soin d’avoir tout en stock : tapis, briques, sangles, matériel de fitness et de musculation, mais aussi serviettes et bouteilles d’eau fraiches sont à votre disposition et en libre-service.
                </p>
            </article>
            <article data-aos="fade"
                data-aos-offset="200"
                data-aos-delay="50"
                data-aos-duration="1000" class="w-60 p-20 ud-m-20 t-a-center">
                <h2 class="ud-p-10 c-green"><i class="w-100 fab fa-pagelines"></i>Prenez soin de vous</h2>
                <p class="ud-p-10">Que vous soyez animé par l’envie de perdre du poids, de préparer un événement sportif, de vous muscler ou de vous remuscler, de vous entretenir ou simplement de vous faire du bien, quoi qu’il en soit vous trouverez ce qu’il vous faut au Garden studio. 
                Venez tester ses cours variés et adaptés à tous. Le Garden studio accueille hommes et femmes de tout âge et de tous niveaux, avec bienveillance et sans préjugés.  
                </p>
            </article>
        </div>
    </section>
</div>