<link rel="stylesheet" href="css/contact.css">
<div class="container">
    <h2 class="ud-p-50 t-a-center c-green">Contact</h2>
    <section class="section_contact ud-p-50 fl-jc-b">
        
        <div class="section_contact_bloc_left w-50">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d42074.971148698896!2d2.502319126720947!3d48.76879819524794!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6095335ddf33d%3A0xa8f583083657db5a!2sSucy-en-Brie!5e0!3m2!1sfr!2sfr!4v1556362485986!5m2!1sfr!2sfr" width="100%" height="300px" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>

        <div class="section_contact_bloc_right w-50">
            <p class="ud-p-20"><a class="normal-link c-green lr-p-10" href="tel:+33631811582"><i class="fas fa-phone"></i></a>Téléphone : <a class="normal-link" href="tel:+33631811582">0631811582</a></p>

            <p class="ud-p-20"><a class="normal-link c-green lr-p-10" href="https://instagram.com/thegardenstudio_?utm_source=ig_profile_share&igshid=16r3x4mlwlxy8" target="_blank"><i class="fab fa-instagram"></i></a><a class="normal-link" href="https://instagram.com/thegardenstudio_?utm_source=ig_profile_share&igshid=16r3x4mlwlxy8">Instagram : Thegardenstudio_</a></p>

            <p class="ud-p-20"><a class="normal-link c-green lr-p-10" href="mailto:contact@thegardenstudio.fr"><i class="far fa-envelope"></i></a>Contactez moi par <a class="normal-link" href="mailto:contact@thegardenstudio.fr">mail</a></p>

            <p class="ud-p-20 "><i class="fas fa-location-arrow lr-p-10"></i>Quartier du Plateau, 94370 Sucy-en-brie</p>
        </div>
    </section>
</div>



