
<link rel="stylesheet" href="css/cours.css">

<div class="container_2">
    <section class="cours_section ud-p-50">
        <div class="cours_section_bloc fl-jc-b">
            <article class="cours_section_bloc_article w-30 p-20 ud-m-10">
                <div class="cours_section_bloc_article_top">
                    <img class="w-100" src="https://via.placeholder.com/250x150" alt="">
                    <h2 class="ud-p-10 t-a-center c-green">Yoga Vinyasa</h2>
                    <p class="ud-p-10">Qui a dit que le yoga était trop calme? Dynamique et intense, le Vinyasa est un yoga qui développe la force, l’équilibre et la souplesse. Il peut s’avérer très amusant avec ses postures d’inversions qui le caractérisent si bien. Chaque séance se terminera par de la relaxation. Apportez de l’attention à vos mouvements, vivez l’instant présent, reconnectez-vous à votre respiration, apprenez à lâcher-prise dans le corps comme dans la tête, et ressortez plus musclé mais aussi plus apaisé et plus détendu.</p>
                </div>
                <div class="button p-20 bg-c-green t-a-center">
                    <a class="normal-link c-white uppercase p-20 " href="yoga-relax.php">En savoir plus</a>
                </div>
                <div class="button p-20 bg-c-green ud-m-10 t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="planning.php">Réserver</a>
                </div>
            </article>

            <article class="cours_section_bloc_article w-30 p-20 ud-m-10">
                <div class="cours_section_bloc_article_top">
                    <img class="w-100" src="https://via.placeholder.com/250x150" alt="">
                    <h2 class="ud-p-10 t-a-center c-green">Pilates Secret'</h2>
                    <p class="ud-p-10">Un cours de pilates dans les règles de l’art tout en y ajoutant une touche de « pep’s » pour des progrès rapides et des résultats visibles ; Dans ce cours, pas de mouvement brusque ni lourdement chargé, mais pas question que ce soit trop facile pour autant. L’accent sera mis sur la sangle abdominale et les fessiers, mais également sur le dos et les bras. Un cours complet pour sculpter la silhouette en profondeur dans le respect de la posture.</p>
                </div>  
                <div class="button p-20 bg-c-green t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="yoga-power.php">En savoir plus</a>
                </div>
                <div class="button p-20 bg-c-green ud-m-10 t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="planning.php">Réserver</a>
                </div>
            </article>

            <article class="cours_section_bloc_article w-30 p-20 ud-m-10">
                <div class="cours_section_bloc_article_top">
                    <img class="w-100" src="https://via.placeholder.com/250x150" alt="">
                    <h2 class="ud-p-10 t-a-center c-green">Circuit Challenge</h2>
                    <p class="ud-p-10">Des exercices de cardio, de gainage renforcement musculaire, le tout sous forme de circuit énergique utilisant toute la palette de matériel existant (barre de squat, corde à sauter, battle rope, TRX, haltères,  kettlebel…)  Une succession d’exercices variés d’une durée de 30 secondes  à 1 min d’effort avec 15 à 30 secondes de récuperation entre chaque poste. 
                    Un cours ou tous les niveaux peuvent se cotoyer puisque chaque atelier dispose d’options de difficultés. Dépassement de soi, perte de poids et renforcement musculaire assurés !</p>
                </div>
                <div class="button p-20 bg-c-green t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="Pilate.php">En savoir plus</a>
                </div>
                <div class="button p-20 bg-c-green ud-m-10 t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="planning.php">Réserver</a>
                </div>
            </article>

            <article class="cours_section_bloc_article w-30 p-20 ud-m-10">
                <div class="cours_section_bloc_article_top">
                    <img class="w-100" src="https://via.placeholder.com/250x150" alt="">
                    <h2 class="ud-p-10 t-a-center c-green">Run & Yoga</h2>
                    <p class="ud-p-10">Le parfait combo pour se défouler et s’apaiser à la fois ! Participez à un cours unique en son genre, le mariage de deux disciplines totalement complémentaires : le running et le Hatha yoga. Le Garden studio n’étant qu’à quelques mètres seulement du parc Omnisports, nous partirons pour 45 min de running dans ce beau parc verdoyant puis nous reviendrons au studio pour 45 min de Hatha yoga, un yoga qui assouplit et qui relaxe. Une succession d’activités d’une excellente logique, pour le corps comme pour l’esprit !</p>
                </div>
                <div class="button p-20 bg-c-green t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="training.php">En savoir plus</a>
                </div>
                <div class="button p-20 bg-c-green ud-m-10 t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="planning.php">Réserver</a>
                </div>
            </article>

            <article class="cours_section_bloc_article w-30 p-20 ud-m-10">
                <div class="cours_section_bloc_article_top">
                    <img class="w-100" src="https://via.placeholder.com/250x150" alt="">
                    <h2 class="ud-p-10 t-a-center c-green">Yoga Master Class</h2>
                    <p class="ud-p-10">Un seul mot d’ordre : prendre le temps ! D’une durée d’1h30, les masterclass disposent d’une précieuse demi-heure de plus que les cours classiques afin de consacrer 30 minutes à l’apprentissage des postures façon atelier ludique. 
                    Je vous accompagnerais individuellement et m’attarderais sur vos diffiicultés afin de vous aider, vous parer, vous donner confiance et vous faire progresser bien plus vite qu’en participant uniquement aux cours classiques. </p>
                </div>
                <div class="button p-20 bg-c-green t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="masterclass.php">En savoir plus</a>
                </div>
                <div class="button p-20 bg-c-green ud-m-10 t-a-center">
                    <a class="normal-link c-white uppercase p-20" href="planning.php">Réserver</a>
                </div>
            </article>

            <article class="cours_section_bloc_article w-30 p-20 ud-m-10">
                <div class="cours_section_bloc_article_top">
                    <img class="w-100" src="https://via.placeholder.com/250x150" alt="">
                    <h2 class="ud-p-10 t-a-center c-green">Coaching Privé</h2>
                    <p class="ud-p-10">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque accusamus deleniti vero hic necessitatibus dicta praesentium error provident reprehenderit dolorem!</p>
                </div> 
                <div class="">
                    <div class="button p-20 bg-c-green t-a-center">
                        <a class="normal-link c-white uppercase p-20" href="coaching.php">En savoir plus</a>
                    </div>
                    <div class="button p-20 bg-c-green ud-m-10 t-a-center">
                        <a class="normal-link c-white uppercase p-20" href="planning.php">Réserver</a>
                    </div>
                </div>
            </article>


        </div>
    </section>
</div>