
<link rel="stylesheet" href="css/galerie.css">

<div class="container">
  <div class="iphone fl-jc-b ud-p-50">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
    <img class="p-20" src="https://via.placeholder.com/500x500" alt="">
  </div>
</div>