<link rel="stylesheet" href="css/index.css">

<div class="container_2 ">
    <div class="index_section_bloc ud-p-50">
        <section class="index_section_logo t-a-center ud-p-50">
            <div class="index_section_logo_about bg-c-pink w-40 m-auto p-30">
                <h2 class="ud-p-50 c-green">Studio de<br> Yoga - Pilates - Coaching</h2>
            </div>
        </section>
    </div>
</div>


<div class="container_2">
    <section class="index_section_concept ud-p-30" id="concept">
        <h1 class="w100 t-a-center c-green uppercase">bienvenue au garden studio !</h1>
        <p class="w-80 m-auto ud-p-20" style="text-align: justify;">
        Bienvenue au Garden studio ! Je m’appelle Elise, j’ai 31 ans, je suis coach sportif diplômée, professeur certifiée de Yoga Hatha et Vinyasa, professeur de Pilates, de Cycling, et maman de deux enfants. C’est avec beaucoup de passion que je cumule toutes ces casquettes.  Ma mission préferée : aider mes élèves à prendre soin d’eux. 
        J’ai créé le Garden studio parce que j’avais très envie de travailler dans un endroit qui me ressemble et dans lequel mes élèves puissent se sentir vraiment bien. Véritable anti-salle de sport, le Garden studio est petit et il a choisi d’en faire un atout : il n’accueille que 6 élèves maximum par cours afin d’offrir un enseignement privilégié et attentif à chacun.  Dans une verrière aux larges baies vitrées entièrement rétractables s’il fait beau, la frontière s’efface entre le dedans et le dehors. Baigné de lumière, la connexion avec la nature rend la pratique magique et l’effort plus agréable. A l’opposé des salles de fitness et de ses diktats, le Garden studio est un havre de paix où vous pourrez faire du sport sans avoir peur de la foule ni du regard des autres. Venez vite en faire votre QG ! Le meilleur endroit pour être bien dans sa peau c’est le Garden studio !</p>
    </section>
</div>