<link rel="stylesheet" href="css/spirit.css">

<div class="container">
    <article class="article_spirit ud-p-50 m-auto">
        <h2 class="uppercase ud-p-20 c-green t-a-center">garden's spirit</h2> 
        <p class="ud-p-10 bold t-a-center">Philosophie et règles de vie du garden studio</p>

        <ul class="article_spirit_list normal-list">
            <div class="w-100">
                <li class="right ud-p-3">
                    <img class="w-50" src="img/spirit/1.jpg" alt="">
                    <div class="article w-50">
                        <h3 class="ud-p-10 c-green">1/ De ta bienveillance tu illumineras</h3>
                        <p>Au garden studio c’est good vibes only! Bienveillance, respect, sourires etattitude positive garantissent une ambiance agréable pour tout le monde.C’est tellement plus chouette de se serrer les coudes quand c’est difficileet de s’applaudir quand c’est dans la poche!</p>
                    </div>
                </li>
            </div>
            <div class="clear"></div>
            <div class="w-100">
                <li class="left ud-p-30">
                    <img class="w-50" src="img/spirit/2.jpg" alt="">
                    <div class="article w-50">
                        <h3 class="ud-p-10 c-green">2/ De la Motivation tu auras</h3>
                        <p>Au garden studio, pas de fausses excuses, pas d’échappatoire, pas deprocrastination ni d’abandon! Avant de te décourager, n’oublie pas que si l’option A est trop difficile il reste l’option B, l’option C et même l’option Z avant l’option Abandon! L’important n’est pas de faire parfait mais de faire deson mieux. C’est tellement plus positif quelqu’un qui fait ce qu’il peutplutôt que quelqu’un qui ne fait rien en se plaignant que c’est trop dur.N’oubliez jamais: «même le dernier d’une course est devant celui qui necourt pas!»</p>
                    </div>
                </li>
            </div>
            <div class="clear"></div>
            <div class="w-100">
                <li class="right ud-p-3">
                    <img class="w-50" src="img/spirit/3.jpg" alt="">
                    <div class="article w-50">
                        <h3 class="ud-p-10 c-green">3/Du studio tu prendras soin</h3>
                        <p>On peut se changer dans un vestiaire qui ne ressemble vraiment pas aux vestiaires froids et tristes des salles de sport. Pas de risque d’avoir froid aux pieds ou de perdre sa clé de casier !
                        Une salle de bain attenante au vestiaire est à votre disposition avec tout le nécessaire pour que vous puissiez vous doucher et vous remaquiller si vous le souhaitez : serviettes, produits de beauté, élastiques et sèche-cheveux sont en libre accès afin que vous puissiez venir les mains vides.</p>
                    </div>
                </li>
            </div>
            <div class="clear"></div>
            <div class="w-100">
                <li class="left ud-p-30">
                    <img class="w-50" src="img/spirit/4.jpg" alt="">
                    <div class="article w-50">
                    <h3 class="ud-p-10 c-green">4/ De partager massivement tu feras</h3>
                    <p>Innondez les réseaux sociaux avec vos story, likez et partagez le compteinstagram, racontez vos aventures et partager vos expériences ! Quand onaime bien on n’a pas peur d’appuyer sur un ptit cœur!</p>
                    </div>
            </li>
            </div>
            <div class="clear"></div>
            <div class="w-100">
                <li class="right ud-p-3">
                    <img class="w-50" src="img/spirit/5.jpg" alt="">
                    <div class="article w-50">
                        <h3 class="ud-p-10 c-green">5/ A l’heure tu seras</h3>
                        <p>Pour le bon déroulement du cours, afin de ne pas déranger les élèves àlheure et faire sonner le visiophone en plein cours, merci d’être à l’heurevoire un peu en avance, votre séance et celle des autres n’en seras queplus agréable!</p>
                    </div>
                </li>
            </div>
        </ul>

        <p class="w-70 m-auto t-a-center ud-p-20 bold">Merci pour votre lecture et je vous souhaite de donner et derecevoir un maximum de bonnes ondes au garden studio !</p>

    </article>
</div>